name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/docker-build.yml'
      - 'Dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/rust-bevy-toolchain:1-bookworm
            ghcr.io/${{ github.repository_owner }}/rust-bevy-toolchain:1.85-bookworm
            ghcr.io/${{ github.repository_owner }}/rust-bevy-toolchain:1.85.0-bookworm
            ghcr.io/${{ github.repository_owner }}/rust-bevy-toolchain:bookworm
            ghcr.io/${{ github.repository_owner }}/rust-bevy-toolchain:1
            ghcr.io/${{ github.repository_owner }}/rust-bevy-toolchain:1.85
            ghcr.io/${{ github.repository_owner }}/rust-bevy-toolchain:1.85.0
            ghcr.io/${{ github.repository_owner }}/rust-bevy-toolchain:latest
            ghcr.io/${{ github.repository_owner }}/rust-bevy-toolchain:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
